version: '3.7'

services:
  production_api:
    container_name: production_api
    build:
      context: ./backend
      dockerfile: ./docker/production/Dockerfile
    expose:
      - 8000
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    env_file:
      - .env.prd
    depends_on:
      - production_db
    entrypoint: ["entrypoint.sh"]

  production_db:
    container_name: production_db
    image: postgres:13.1
    env_file:
      - .env.prd
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  production_api_proxy:
    container_name: production_api_proxy
    build: ./proxy_backend
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
    ports:
      - "6969:80"
    depends_on:
      - production_api
      - production_db

  production_app:
    container_name: production_app
    build: ./frontend
    ports:
      - "8080:8080"
    env_file:
      - .env.prd
    depends_on:
      - production_api
      - production_db
      - production_api_proxy

volumes:
  static_data:
  media_data:
  postgres_data: