version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./backend:/code
      - static_data:/vol/web
      - media_data:/vol/web/media
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db
    entrypoint: ["entrypoint-dev.sh"]

  db:
    container_name: db
    image: postgres:13.1
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: app
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile-dev
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - db

volumes:
  static_data:
  media_data:
  postgres_data: