version: '3.7'

services:
  api:
    container_name: api
    build: ./backend
    restart: on-failure
    volumes:
      - ./backend:/code
      - static_data:/vol/web
    ports:
      - "8000:8000"
    env_file:
      - dev.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13.1
    restart: always
    env_file:
      - dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  app:
    container_name: app
    build: ./frontend
    restart: on-failure
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    env_file:
      - dev.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
      - db

volumes:
  static_data:
  postgres_data: